clean up

diff --git a/language_pack/localization/custom_languages/scripts/getNor b/language_pack/localization/custom_languages/scripts/getNor
--- a/language_pack/localization/custom_languages/scripts/getNor
+++ b/language_pack/localization/custom_languages/scripts/getNor
@@ -2,11 +2,9 @@
 
 source /etc/preinit
 script_init
-customLangURL="http://hakchicloud.com/Hakchi_Themes/options_menu/customlangs"
-addonPath="$mountpoint/etc/options_menu/shonen"
-countryCode="eur_nor"
 
-cd "$addonPath"
+language="Norwegian"
+countryCode="eur_nor"
 
 echo "  _  _                         _           "
 echo " | \\| |___ _ ___ __ _____ __ _(_)__ _ _ _  "
@@ -14,23 +12,47 @@ echo " | .\` / _ \\ '_\\ V  V / -_) _\` | / _\` | ' \\ "
 echo " |_|\\_\\___/_|  \\_/\\_/\\___\\__, |_\\__,_|_||_|"
 echo "                         |___/             "
 echo ""
-echo "Translation: Chinspanker"
+echo "$language Translation: Chinspanker"
 echo "Shonen Jump Convertion: DefKorns"
 echo ""
 echo "Checking localization files."
+customLangURL="http://hakchicloud.com/Hakchi_Themes/options_menu/customlangs"
+addonPath="$mountpoint/etc/options_menu/shonen"
+scriptPath="$addonPath/scripts"
+customLangDir="$addonPath/custom_languages"
+
+cd "$addonPath" || exit
+
 wget -q --spider "$customLangURL"/$countryCode.tar.gz
 
 if [ $? -eq 0 ]; then
-echo "Downloading..."
-wget "$customLangURL"/$countryCode.tar.gz
+	echo "Downloading..."
+	wget "$customLangURL"/$countryCode.tar.gz
 
-echo "Unpacking language..."
+	echo "Unpacking language..."
 	tar -xzf $countryCode.tar.gz && rm -f ./*.tar.gz
-    sleep 2
+	echo "Checking for $countryCode font support..."
+	if [ ! -d "$customLangDir/fonts" ]; then
+		cd "$customLangDir" || exit
+		wget "$customLangURL"/fonts.tar.gz
+		tar -xzf fonts.tar.gz && rm -f ./*.tar.gz
+	fi
+
+    echo "COMMAND_NAME=Translate to $language
+COMMAND_TYPE=INTERNAL
+RESTART_UI=FALSE
+COMMAND_STR=sh $scriptPath/$countryCode && usleep 50000 && hakchi reboot
+PREVIEW_IMAGE=$customLangDir/$countryCode.png
+PREVIEW_IMAGE_X=590
+PREVIEW_IMAGE_Y=248" >"$addonPath/commands/c0008_$countryCode"
+
+sed -r "s/COUNTRYCODEHERE/${countryCode}/g;s/LANGUAGEHERE/${language}/g;" "$scriptPath/_template" >"$scriptPath/$countryCode"
+
+	sleep 2
 	echo "Complete."
 	echo "Custom language now available and ready to use from the list."
 else
-   echo "Something may be wrong here."
-   echo "Could not find the selected theme,"
-   echo "check your internet connection. "
+	echo "Something may be wrong here."
+	echo "Could not find the selected theme,"
+	echo "check your internet connection. "
 fi
